import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  IBM_Plex_Serif,
  Fira_Sans,
  Roboto,
  Press_Start_2P,
} from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { Footer } from "@/components/layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ibmPlexSerif = IBM_Plex_Serif({
  weight: "400",
  variable: "--font-ibm-plex-serif",
  subsets: ["latin"],
});

const firaSans = Fira_Sans({
  weight: "400",
  variable: "--font-fira_sans",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: "400",
  variable: "--font-roboto",
  subsets: ["latin"],
});

const pokemon = Press_Start_2P({
  weight: "400",
  variable: "--font-press_start_2p",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TT Web Development & Design",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${roboto.variable} ${pokemon.variable} antialiased container`}
      >
        <Header />
        <div className="">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
